version: "3.9"

services:
  web_api:
    build:
      context: .
      target: build
    volumes:
      - .:/web
    command: /web/gradlew bootRun
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: "database"
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
